'use client';

// Central mock data store — replaces database in this demo
export const mockUser = {
  id: 'user_001',
  name: 'Alex Rivera',
  email: 'alex.rivera@gmail.com',
  provider: 'google',
  replyTone: 'professional',
  notifyInApp: true,
  notifyDigest: false,
  connected: true,
};

export const mockEmails = [
  {
    id: 'em_001',
    sender_name: 'Sarah Chen',
    sender_email: 'sarah.chen@designco.com',
    subject: 'Q3 mockups ready for your review',
    received_at: new Date(Date.now() - 8 * 60000).toISOString(),
    needs_reply: true,
    category: 'action_request',
    urgency: 'high',
    ai_summary: "Sarah's asking you to review the Q3 design mockups and share feedback before this Friday's team meeting.",
    sender_type: 'colleague',
    body_plain: `Hi Alex,\n\nThe Q3 mockups are finally done and uploaded to Figma. Could you take a look before Friday? We need your sign-off before the team meeting.\n\nHere's the link: figma.com/q3-designs\n\nLet me know if you have any questions!\n\nBest,\nSarah`,
    draft: {
      id: 'dr_001',
      status: 'pending_approval',
      body: `Hi Sarah,\n\nThanks for sending these over — I'll take a look at the Q3 mockups in Figma and get you my feedback before Friday.\n\nIf anything stands out that needs a quick call to discuss, I'll ping you.\n\nBest,\nAlex`,
    },
  },
  {
    id: 'em_002',
    sender_name: 'Mark Johnson',
    sender_email: 'mark.johnson@clientcorp.com',
    subject: 'Re: Johnson Contract — final terms',
    received_at: new Date(Date.now() - 35 * 60000).toISOString(),
    needs_reply: true,
    category: 'direct_question',
    urgency: 'high',
    ai_summary: "Mark is following up on the contract final terms and asking if you can hop on a call this week to align before signing.",
    sender_type: 'client',
    body_plain: `Alex,\n\nFollowing up on the contract we discussed. We've reviewed the updated terms and we're mostly aligned. Can we set up a 30-min call this week to go over the last two points before we sign?\n\nWorks best for me: Wednesday or Thursday afternoon.\n\nRegards,\nMark`,
    draft: {
      id: 'dr_002',
      status: 'pending_approval',
      body: `Hi Mark,\n\nGreat to hear the terms are mostly aligned — we're getting close! Thursday afternoon works well for me. How does 2:00 PM sound? I'll send a calendar invite.\n\nLooking forward to wrapping this up.\n\nBest,\nAlex`,
    },
  },
  {
    id: 'em_003',
    sender_name: 'Stripe',
    sender_email: 'receipts@stripe.com',
    subject: 'Your July invoice is ready — $49.00',
    received_at: new Date(Date.now() - 2 * 3600000).toISOString(),
    needs_reply: false,
    category: 'receipt',
    urgency: 'low',
    ai_summary: "Your Stripe subscription invoice for $49 in July has been processed. No action needed.",
    sender_type: 'automated',
    body_plain: 'Invoice #INV-2026-0742\nAmount: $49.00\nStatus: Paid\nDate: July 27, 2026',
    draft: null,
  },
  {
    id: 'em_004',
    sender_name: 'Priya Mehta',
    sender_email: 'p.mehta@startup.io',
    subject: 'Quick question about the API integration',
    received_at: new Date(Date.now() - 4 * 3600000).toISOString(),
    needs_reply: true,
    category: 'direct_question',
    urgency: 'medium',
    ai_summary: "Priya has a quick question about authenticating with your API — she's getting a 401 error and wants to know if there's a step she's missing.",
    sender_type: 'colleague',
    body_plain: `Hey Alex,\n\nI'm trying to connect to the API using the token you shared last week, but I keep getting a 401 Unauthorized. Am I missing an additional header or scope?\n\nThanks,\nPriya`,
    draft: {
      id: 'dr_004',
      status: 'pending_approval',
      body: `Hey Priya,\n\nThe 401 usually means the Authorization header format is off. Make sure you're sending it as: Authorization: Bearer <your-token> (not Basic or without the "Bearer" prefix).\n\nAlso double-check that the token hasn't expired — they rotate every 24 hours. If you're still stuck, share the request headers and I can take a look.\n\nAlex`,
    },
  },
  {
    id: 'em_005',
    sender_name: 'GitHub',
    sender_email: 'noreply@github.com',
    subject: '[GitHub] A new device signed in to your account',
    received_at: new Date(Date.now() - 6 * 3600000).toISOString(),
    needs_reply: false,
    category: 'notification',
    urgency: 'low',
    ai_summary: "GitHub is letting you know a new device signed into your account. It was likely you — but worth checking if it wasn't.",
    sender_type: 'automated',
    body_plain: 'A new device signed in to your GitHub account. If this was you, no action is needed.',
    draft: null,
  },
  {
    id: 'em_006',
    sender_name: 'TechCrunch Daily',
    sender_email: 'newsletter@techcrunch.com',
    subject: "Today's top stories: AI funding rounds hit record highs",
    received_at: new Date(Date.now() - 8 * 3600000).toISOString(),
    needs_reply: false,
    category: 'newsletter',
    urgency: 'low',
    ai_summary: "TechCrunch's daily digest. Today's lead: AI startup funding hit a new quarterly record. No action needed.",
    sender_type: 'automated',
    body_plain: "Today's headlines from TechCrunch. AI funding rounds reach $40B this quarter...",
    draft: null,
  },
];

export const mockNotifications = [
  { id: 'n1', type: 'new_email', text: 'New email from Sarah Chen', time: '8m ago', read: false },
  { id: 'n2', type: 'new_email', text: 'Mark Johnson replied about the contract', time: '35m ago', read: false },
  { id: 'n3', type: 'sent', text: 'Reply sent to Priya Mehta', time: '2h ago', read: true },
];
