'use client';

// Default Demo / Public Visitor User profile
export const mockUser = {
  email: 'alex.morgan@mailmind.ai',
  name: 'Alex Morgan',
  provider: 'gmail',
  tone: 'professional',
  connected: true,
  isDemo: true,
  avatar: null,
  avatarColor: '#6c63ff',
  inApp: true,
  digest: false,
  savedAt: '2026-08-23T12:00:00.000Z'
};

// Rich sample emails for Live Demo & Public Agent Lookback
export const mockEmails = [
  {
    id: 'msg_101',
    seqno: 101,
    uid: 101,
    sender: 'Sarah Lin',
    sender_name: 'Sarah Lin',
    sender_email: 'sarah.lin@apexcloud.io',
    senderEmail: 'sarah.lin@apexcloud.io',
    subject: 'Urgent: Q3 Partnership Agreement review needed by 5 PM',
    received_at: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    receivedAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    body_plain: `Hi Alex,\n\nI hope you're having a productive week. We have finalized the terms for the Q3 joint partnership agreement with CloudScale. Could you please review Section 4 (SLA & Uptime guarantees) and give us your final sign-off before 5:00 PM today?\n\nLet me know if any clauses need adjustment.\n\nBest,\nSarah Lin\nVP of Partnerships | ApexCloud`,
    body: `<p>Hi Alex,</p><p>I hope you're having a productive week. We have finalized the terms for the Q3 joint partnership agreement with CloudScale. Could you please review Section 4 (SLA &amp; Uptime guarantees) and give us your final sign-off before 5:00 PM today?</p><p>Let me know if any clauses need adjustment.</p><p>Best,<br>Sarah Lin<br>VP of Partnerships | ApexCloud</p>`,
    category: 'action_request',
    needs_reply: true,
    needsReply: true,
    urgency: 'high',
    ai_summary: 'Sarah requests final review and sign-off on Section 4 of the Q3 Partnership Agreement before 5:00 PM today.',
    summary: 'Sarah requests final review and sign-off on Section 4 of the Q3 Partnership Agreement before 5:00 PM today.',
    draft: {
      id: 'dr_msg_101',
      status: 'pending_approval',
      body: `Hi Sarah,\n\nThank you for sharing the updated agreement. I am reviewing Section 4 regarding the SLA & Uptime guarantees right now and will provide our sign-off before the 5:00 PM deadline.\n\nBest regards,\nAlex Morgan`
    },
    draftBody: `Hi Sarah,\n\nThank you for sharing the updated agreement. I am reviewing Section 4 regarding the SLA & Uptime guarantees right now and will provide our sign-off before the 5:00 PM deadline.\n\nBest regards,\nAlex Morgan`,
    draftStatus: 'pending'
  },
  {
    id: 'msg_102',
    seqno: 102,
    uid: 102,
    sender: 'David Chen',
    sender_name: 'David Chen',
    sender_email: 'david.chen@technova.com',
    senderEmail: 'david.chen@technova.com',
    subject: 'Question regarding the API rate limiting proposal',
    received_at: new Date(Date.now() - 1000 * 60 * 85).toISOString(),
    receivedAt: new Date(Date.now() - 1000 * 60 * 85).toISOString(),
    body_plain: `Hey Alex,\n\nI was going through the latest RFC on our backend architecture. What do you think about setting the default burst limit to 250 requests/second instead of 100 for enterprise tiers?\n\nWould love to hear your thoughts before our architecture sync on Thursday.\n\nThanks,\nDavid`,
    body: `<p>Hey Alex,</p><p>I was going through the latest RFC on our backend architecture. What do you think about setting the default burst limit to 250 requests/second instead of 100 for enterprise tiers?</p><p>Would love to hear your thoughts before our architecture sync on Thursday.</p><p>Thanks,<br>David</p>`,
    category: 'direct_question',
    needs_reply: true,
    needsReply: true,
    urgency: 'medium',
    ai_summary: 'David asks for your opinion on increasing enterprise tier burst limits to 250 req/s before Thursday sync.',
    summary: 'David asks for your opinion on increasing enterprise tier burst limits to 250 req/s before Thursday sync.',
    draft: {
      id: 'dr_msg_102',
      status: 'pending_approval',
      body: `Hi David,\n\nThanks for reaching out. Setting the burst limit to 250 req/s for enterprise tiers makes sense given their concurrency patterns, provided our Redis cluster handles the spike. Let's discuss the Redis memory footprint in Thursday's sync.\n\nBest regards,\nAlex Morgan`
    },
    draftBody: `Hi David,\n\nThanks for reaching out. Setting the burst limit to 250 req/s for enterprise tiers makes sense given their concurrency patterns, provided our Redis cluster handles the spike. Let's discuss the Redis memory footprint in Thursday's sync.\n\nBest regards,\nAlex Morgan`,
    draftStatus: 'pending'
  },
  {
    id: 'msg_103',
    seqno: 103,
    uid: 103,
    sender: 'Stripe Billing',
    sender_name: 'Stripe Billing',
    sender_email: 'invoices@stripe.com',
    senderEmail: 'invoices@stripe.com',
    subject: 'Receipt for Invoice #INV-2026-9482 ($79.00 USD)',
    received_at: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    receivedAt: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    body_plain: `Your payment of $79.00 USD to Supabase Enterprise has been processed successfully. Invoice ID: INV-2026-9482. Payment method: Visa ending in 4242. Date: August 23, 2026. View your full invoice details in your dashboard.`,
    body: `<p>Your payment of $79.00 USD to Supabase Enterprise has been processed successfully.</p><p>Invoice ID: INV-2026-9482<br>Payment method: Visa ending in 4242<br>Date: August 23, 2026</p>`,
    category: 'receipt',
    needs_reply: false,
    needsReply: false,
    urgency: 'low',
    ai_summary: 'Monthly receipt of $79.00 for Supabase Enterprise. Payment succeeded via Visa ····4242.',
    summary: 'Monthly receipt of $79.00 for Supabase Enterprise. Payment succeeded via Visa ····4242.',
    draft: null,
    draftBody: null,
    draftStatus: null
  },
  {
    id: 'msg_104',
    seqno: 104,
    uid: 104,
    sender: 'The AI Dispatch',
    sender_name: 'The AI Dispatch',
    sender_email: 'newsletter@aidispatch.co',
    senderEmail: 'newsletter@aidispatch.co',
    subject: 'Issue #88: Autonomous Agents in Production & Zero-Shot Email Classification',
    received_at: new Date(Date.now() - 1000 * 60 * 600).toISOString(),
    receivedAt: new Date(Date.now() - 1000 * 60 * 600).toISOString(),
    body_plain: `Welcome to Issue #88 of The AI Dispatch!\n\nThis week in AI:\n• Autonomous agent frameworks are adopting permission-first architectures to mitigate unauthorized actions.\n• Local small language models achieve 94% accuracy on contextual email categorization.\n• Real-time IMAP telemetry and asynchronous mail parsers.\n\nRead more at aidispatch.co`,
    body: `<p>Welcome to Issue #88 of The AI Dispatch!</p><p>This week in AI:<br>• Autonomous agent frameworks are adopting permission-first architectures.<br>• Local small language models achieve 94% accuracy on contextual email categorization.<br>• Real-time IMAP telemetry and asynchronous mail parsers.</p>`,
    category: 'newsletter',
    needs_reply: false,
    needsReply: false,
    urgency: 'low',
    ai_summary: 'Weekly AI newsletter covering autonomous agent permission systems and email categorization benchmarks.',
    summary: 'Weekly AI newsletter covering autonomous agent permission systems and email categorization benchmarks.',
    draft: null,
    draftBody: null,
    draftStatus: null
  },
  {
    id: 'msg_105',
    seqno: 105,
    uid: 105,
    sender: 'Google Security',
    sender_name: 'Google Security',
    sender_email: 'no-reply@accounts.google.com',
    senderEmail: 'no-reply@accounts.google.com',
    subject: 'Security Alert: New sign-in from Chrome on macOS',
    received_at: new Date(Date.now() - 1000 * 60 * 1200).toISOString(),
    receivedAt: new Date(Date.now() - 1000 * 60 * 1200).toISOString(),
    body_plain: `Your Google Account was just accessed from a new device (Chrome on macOS, IP 192.0.2.1). If this was you, no action is required. If this was not you, review your account security immediately.`,
    body: `<p>Your Google Account was just accessed from a new device (Chrome on macOS, IP 192.0.2.1). If this was you, no action is required.</p>`,
    category: 'notification',
    needs_reply: false,
    needsReply: false,
    urgency: 'high',
    ai_summary: 'Automated Google Security notice: New sign-in detected from Chrome on macOS.',
    summary: 'Automated Google Security notice: New sign-in detected from Chrome on macOS.',
    draft: null,
    draftBody: null,
    draftStatus: null
  },
  {
    id: 'msg_106',
    seqno: 106,
    uid: 106,
    sender: 'Elena Rostova',
    sender_name: 'Elena Rostova',
    sender_email: 'elena.rostova@vectorlabs.ai',
    senderEmail: 'elena.rostova@vectorlabs.ai',
    subject: 'Feedback on autonomous email agent demo',
    received_at: new Date(Date.now() - 1000 * 60 * 1800).toISOString(),
    receivedAt: new Date(Date.now() - 1000 * 60 * 1800).toISOString(),
    body_plain: `Hi Alex,\n\nI tried out the MailMind autonomous agent live link demo today — the permission-first drafting model is incredible! Can we schedule a 15-minute call tomorrow afternoon to discuss integrating MailMind with our team inbox?\n\nBest,\nElena`,
    body: `<p>Hi Alex,</p><p>I tried out the MailMind autonomous agent live link demo today — the permission-first drafting model is incredible! Can we schedule a 15-minute call tomorrow afternoon to discuss integrating MailMind with our team inbox?</p><p>Best,<br>Elena</p>`,
    category: 'direct_question',
    needs_reply: true,
    needsReply: true,
    urgency: 'medium',
    ai_summary: 'Elena loved the MailMind live demo and wants to schedule a 15-minute call tomorrow afternoon for team integration.',
    summary: 'Elena loved the MailMind live demo and wants to schedule a 15-minute call tomorrow afternoon for team integration.',
    draft: {
      id: 'dr_msg_106',
      status: 'pending_approval',
      body: `Hi Elena,\n\nThank you for testing out MailMind! I'd be delighted to walk you through our team inbox integrations. Tomorrow afternoon at 3:00 PM works great on my end. I will send over a calendar invite shortly.\n\nBest regards,\nAlex Morgan`
    },
    draftBody: `Hi Elena,\n\nThank you for testing out MailMind! I'd be delighted to walk you through our team inbox integrations. Tomorrow afternoon at 3:00 PM works great on my end. I will send over a calendar invite shortly.\n\nBest regards,\nAlex Morgan`,
    draftStatus: 'pending'
  }
];

export const mockNotifications = [
  { id: 'n1', type: 'connected', text: 'MailMind Autonomous Agent connected & live', time: 'Just now', read: false },
  { id: 'n2', type: 'system', text: 'Permission-first reply protection active', time: 'Just now', read: false },
  { id: 'n3', type: 'draft', text: 'Draft ready for Sarah Lin (Q3 Agreement)', time: '25m ago', read: false }
];

